### ISSUE TITLE
LogBasket NullPointerException

### ISSUE THREAD

**Issue by CreativeTechGuy** [MosheBenZacharia/GP-Per-Hour#31]
Running version 1.1. Chopped log and got this error in the console.

```
java.lang.NullPointerException: null
	at com.gpperhour.itemcharges.items.U_LogBasket.lambda$new$2(U_LogBasket.java:90)
	at com.gpperhour.itemcharges.ChargedItem.onChatMessage(ChargedItem.java:477)
	at com.gpperhour.itemcharges.ChargedItemManager.lambda$onChatMessage$0(ChargedItemManager.java:148)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
	at com.gpperhour.itemcharges.ChargedItemManager.onChatMessage(ChargedItemManager.java:148)
	at net.runelite.client.eventbus.EventBus$Subscriber.invoke(EventBus.java:70)
	at net.runelite.client.eventbus.EventBus.post(EventBus.java:223)
	at net.runelite.client.callback.Hooks.post(Hooks.java:194)
	at gm.al(gm.java:18811)
	at pe.ac(pe.java:19)
	at client.kq(client.java:49047)
	at client.hw(client.java:3098)
	at client.ai(client.java:1124)
	at bb.ad(bb.java:358)
	at bb.run(bb.java:335)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by MosheBenZacharia** [comment]
taking a look now

**Comment by MosheBenZacharia** [comment]
seems harmless but I pushed a fix to my pending PR here: https://github.com/runelite/plugin-hub/pull/5089 will close this when it merges.
